stages:
  - build-base-image
  - build-outline

build-base-image:
  stage: build-base-image
  script:
    - nvm use v14
    - export DOCKER_FIILE=Dockerfile.base
    - export DOCKER_PUBLISH_URL=registry.cn-qingdao.aliyuncs.com/nobook/outline_base_image
    - ci-build
  tags:
    - build-60.205.200.125

build-outline:
  stage: build-outline
  script:
    - nvm use v14
    - export DOCKER_FIILE=Dockerfile
    - unset DOCKER_PUBLISH_URL
    - ci-build
  tags:
    - build-60.205.200.125